INSERT INTO block
( session_id, block_type_id)
VALUES
($1, $2)
RETURNING *;


-- WILL NEED TO SEND BACK THIS SINGLE BLOCK'S INFO ... (NOT ALL BLOCKS, AS WE WILL BE IMMEDIATELY ROUTING TO THIS ONE BLOCK UPON RECEIVING BLOCK INFO ON THE FRONT END) --

